### ISSUE TITLE
Tests have started to fail (with PPI dev release 1.280?)

### ISSUE THREAD

**Issue by andk** [moznion/Test-Synopsis-Expectation#6]
Sample fail report: http://www.cpantesters.org/cpan/report/8cc1f27c-c2f7-11ef-a9da-9dcdaa4a55fe

@wchristian , you may be interested in this test failure.

So far my only proof that the upgrade of PPI made the test fail happened with an upgrade of a perl 5.40.0, not the one in the above linked report. Let me know if further evidence is required.

**Comment by wchristian** [comment]
@andk Much appreciated, that is indeed a failure caused by me and i will try and address it on PPI's side.

**Comment by andk** [comment]
PPI 1.281 seems to have this problem fixed; Thank You to @wchristian ! I'll close this issue now

**Comment by wchristian** [comment]
Thanks for being on top of this, @andk. :)
